<a href="https://colab.research.google.com/github/LOVELY1907/SAP_AI-ML-DL/blob/main/02_Machine_Learning/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
#Data Ingestion
df = pd.read_csv('/content/LPA_regression_dataset.csv')

In [ ]:
df.sample(5)

     Age  Experience_Years  ... Performance_Score        LPA
354   25              34.0  ...          2.240967  23.699847
225   57              24.0  ...          8.515594  23.651128
63    53              21.0  ...          1.673391  14.500585
859   48              23.0  ...          4.803904  19.250598
388   34              31.0  ...          8.603761  29.032687

[5 rows x 7 columns]

In [ ]:
def Data_cleaning(df):
  #null values
  null_values = df.isnull().sum()
  print(null_values)

  #duplicate
  duplicate_values = df.duplicated().sum()
  print(duplicate_values)

  #information of data
  df.info()

  #describe
  df.describe()

In [ ]:
from inspect import AGEN_CLOSED
#calling function
Data_cleaning(df)

Age                  0
Experience_Years     3
Education_Level      0
Department           0
City                 0
Performance_Score    0
LPA                  0
dtype: int64
0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Experience_Years   997 non-null    float64
 2   Education_Level    1000 non-null   object
 3   Department         1000 non-null   object
 4   City               1000 non-null   object
 5   Performance_Score  1000 non-null   float64
 6   LPA                1000 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 54.8+ KB

In [ ]:
#handling Missing Values
def Handling_missing_vale(key:str):
  df[key] = df[key].fillna(df[key].mean())

In [ ]:
Handling_missing_vale('Experience_Years')

In [ ]:
df['Experience_Years'].isnull().sum()

np.int64(0)

In [ ]:
df.select_dtypes(include='object').columns

Index(['Education_Level', 'Department', 'City'], dtype='object')

In [ ]:
df['Education_Level'].unique()

array(['PhD', 'Bachelor', 'Diploma', 'Master', 'High School'],
      dtype=object)

In [ ]:
#Applying Encoding
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

#One HOt Encoder object -> fit transform #City
ohe = OneHotEncoder(sparse_output=False)

#Ordinal Encoder object #Education_level
odc = OrdinalEncoder()

#label Encoder object #Department
lbc = LabelEncoder()



df['Department'] = lbc.fit_transform(df['Department'])
df[['Education_Level']] = odc.fit_transform(df[['Education_Level']])
df['City'] = ohe.fit_transform(df[['City']])

In [ ]:
df.sample(3)

     Age  Experience_Years  Education_Level  ...  City  Performance_Score        LPA
830   25              29.0              0.0  ...   0.0           5.769733  21.918873
617   49               9.0              2.0  ...   0.0           2.290558   8.219964
748   48               8.0              1.0  ...   0.0           6.867108  16.296319

[3 rows x 7 columns]

In [ ]:
#model Building
X = df.drop('LPA',axis=1)
y = df['LPA']

In [ ]:
#training as testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(800, 6)

In [ ]:
y_train.shape

(800,)

In [ ]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test,y_pred)
print(mae)

1.5276916372065974

In [ ]:
r2_score(y_test,y_pred)

0.8900664063665468

In [ ]:
sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [ ]:
lr2 = LinearRegression()
lr2.fit(X_train_scaled,y_train)

LinearRegression()