<a href="https://colab.research.google.com/github/LOVELY1907/SAP_AI-ML-DL/blob/main/02_Machine_Learning/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
#Data Ingestion
df = pd.read_csv('/content/Diagnostic Breast Cancer Dataset (1).csv')

In [ ]:
df.sample(5)

,ID,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension,Diagnosis
561,925311,11.20,29.37,70.67,386.0,0.07449,0.03558,0.00000,0.00000,0.1060,...,38.30,75.19,439.6,0.09267,0.05494,0.0000,0.00000,0.1566,0.05905,Benign
480,912193,12.16,18.03,78.29,455.3,0.09087,0.07838,0.02916,0.01527,0.1464,...,27.87,88.83,547.4,0.12080,0.22790,0.1620,0.05690,0.2406,0.07729,Benign
164,8712289,23.27,22.04,152.10,1686.0,0.08439,0.11450,0.13240,0.09702,0.1801,...,28.22,184.20,2403.0,0.12280,0.35830,0.3948,0.23460,0.3589,0.09187,Malignant
189,874839,12.30,15.90,78.83,463.7,0.08080,0.07253,0.03844,0.01654,0.1667,...,19.59,86.65,546.7,0.10960,0.16500,0.1423,0.04815,0.2482,0.06306,Benign
367,9011495,12.21,18.02,78.31,458.4,0.09231,0.07175,0.04392,0.02027,0.1695,...,24.04,93.85,624.6,0.13680,0.21700,0.2413,0.08829,0.3218,0.07470,Benign

In [ ]:
df.shape

(569, 32)

In [ ]:
df.drop('ID',axis=1)

,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,Mean Fractal Dimension,...,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,Malignant
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,Malignant
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,Malignant
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,Malignant
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,Malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,Malignant
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,Malignant
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,Malignant
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,Malignant
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,Benign

In [ ]:
df.isnull().sum()

ID                         0
Mean Radius                0
Mean Texture               0
Mean Perimeter             0
Mean Area                  0
Mean Smoothness            0
Mean Compactness           0
Mean Concavity             0
Mean Concave Points        0
Mean Symmetry              0
Mean Fractal Dimension     0
Radius SE                  0
Texture SE                 0
Perimeter SE               0
Area SE                    0
Smoothness SE              0
Compactness SE             0
Concavity SE               0
Concave Points SE          0
Symmetry SE                0
Fractal Dimension SE       0
Worst Radius               0
Worst Texture              0
Worst Perimeter            0
Worst Area                 0
Worst Smoothness           0
Worst Compactness          0
Worst Concavity            0
Worst Concave Points       0
Worst Symmetry             0
Worst Fractal Dimension    0
Diagnosis                  0
dtype: int64

In [ ]:
df['Diagnosis'].value_counts()

Diagnosis
0    357
1    212
Name: count, dtype: int64

In [ ]:
lbc = LabelEncoder()
df['Diagnosis'] = lbc.fit_transform(df['Diagnosis'])

In [ ]:
df.sample(5)

,ID,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension,Diagnosis
49,857156,13.49,22.30,86.91,561.0,0.08752,0.07698,0.04751,0.03384,0.1809,...,31.82,99.0,698.8,0.1162,0.1711,0.2282,0.1282,0.2871,0.06917,0
23,851509,21.16,23.04,137.20,1404.0,0.09428,0.10220,0.10970,0.08632,0.1769,...,35.59,188.0,2615.0,0.1401,0.2600,0.3155,0.2009,0.2822,0.07526,1
323,895100,20.34,21.51,135.90,1264.0,0.11700,0.18750,0.25650,0.15040,0.2569,...,31.86,171.1,1938.0,0.1592,0.4492,0.5344,0.2685,0.5558,0.10240,1
461,911296202,27.42,26.27,186.90,2501.0,0.10840,0.19880,0.36350,0.16890,0.2061,...,31.37,251.2,4254.0,0.1357,0.4256,0.6833,0.2625,0.2641,0.07427,1
129,866674,19.79,25.12,130.40,1192.0,0.10150,0.15890,0.25450,0.11490,0.2202,...,33.58,148.7,1589.0,0.1275,0.3861,0.5673,0.1732,0.3305,0.08465,1

In [ ]:
X = df.drop('Diagnosis',axis=1)
Y = df['Diagnosis']

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2, random_state=100, stratify= Y)

In [ ]:
X_train

,ID,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
409,905501,12.27,17.92,78.41,466.1,0.08685,0.06526,0.032110,0.02653,0.1966,...,14.10,28.88,89.00,610.2,0.12400,0.17950,0.13770,0.09532,0.3455,0.06896
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.092510,0.05302,0.1590,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.34030,0.14180,0.2218,0.07820
80,861103,11.45,20.97,73.81,401.5,0.11020,0.09362,0.045910,0.02233,0.1842,...,13.11,32.16,84.53,525.1,0.15570,0.16760,0.17550,0.06127,0.2762,0.08851
148,86973702,14.44,15.18,93.97,640.1,0.09970,0.10210,0.084870,0.05532,0.1724,...,15.85,19.85,108.60,766.9,0.13160,0.27350,0.31030,0.15990,0.2691,0.07683
212,8810703,28.11,18.47,188.50,2499.0,0.11420,0.15160,0.320100,0.15950,0.1648,...,28.11,18.47,188.50,2499.0,0.11420,0.15160,0.32010,0.15950,0.1648,0.05525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,911408,12.83,15.73,82.89,506.9,0.09040,0.08269,0.058350,0.03078,0.1705,...,14.09,19.35,93.22,605.8,0.13260,0.26100,0.34760,0.09783,0.3006,0.07802
113,864292,10.51,20.19,68.64,334.2,0.11220,0.13030,0.064760,0.03068,0.1922,...,11.16,22.75,72.62,374.4,0.13000,0.20490,0.12950,0.06136,0.2383,0.09026
243,88411702,13.75,23.77,88.54,590.0,0.08043,0.06807,0.046970,0.02344,0.1773,...,15.01,26.34,98.00,706.0,0.09368,0.14420,0.13590,0.06106,0.2663,0.06321
493,914101,12.46,12.83,78.83,477.3,0.07372,0.04043,0.007173,0.01149,0.1613,...,13.19,16.36,83.24,534.0,0.09439,0.06477,0.01674,0.02680,0.2280,0.07028
199,877500,14.45,20.22,94.49,642.7,0.09872,0.12060,0.118000,0.05980,0.1950,...,18.33,30.12,117.90,1044.0,0.15520,0.40560,0.49670,0.18380,0.4753,0.10130

In [ ]:
Y_train

409    0
566    1
80     0
148    0
212    1
      ..
475    0
113    0
243    0
493    0
199    1
Name: Diagnosis, Length: 455, dtype: int64

In [ ]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [ ]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled,Y_train)

LogisticRegression(max_iter=1000)

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr,X_train_scaled,Y_train,cv=5)

array([0.98901099, 0.96703297, 0.97802198, 0.94505495, 0.96703297])

In [ ]:
Y_pred = lr.predict(X_test_scaled)

In [ ]:
Y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0])

In [ ]:
X_test_scaled.shape

(114, 31)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9736842105263158

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9736842105263158

In [ ]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(lr,X_train_scaled,Y_train,cv=50)
print(score.mean())
print(score.min())
print(score.max())

0.9735555555555557
0.7777777777777778
1.0

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9736842105263158

In [ ]:
from sklearn.metrics import r2_score
r2_score(Y_test,Y_pred)

0.8869047619047619

In [ ]:
X_train

,ID,Mean Radius,Mean Texture,Mean Perimeter,Mean Area,Mean Smoothness,Mean Compactness,Mean Concavity,Mean Concave Points,Mean Symmetry,...,Worst Radius,Worst Texture,Worst Perimeter,Worst Area,Worst Smoothness,Worst Compactness,Worst Concavity,Worst Concave Points,Worst Symmetry,Worst Fractal Dimension
409,905501,12.27,17.92,78.41,466.1,0.08685,0.06526,0.032110,0.02653,0.1966,...,14.10,28.88,89.00,610.2,0.12400,0.17950,0.13770,0.09532,0.3455,0.06896
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.092510,0.05302,0.1590,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.34030,0.14180,0.2218,0.07820
80,861103,11.45,20.97,73.81,401.5,0.11020,0.09362,0.045910,0.02233,0.1842,...,13.11,32.16,84.53,525.1,0.15570,0.16760,0.17550,0.06127,0.2762,0.08851
148,86973702,14.44,15.18,93.97,640.1,0.09970,0.10210,0.084870,0.05532,0.1724,...,15.85,19.85,108.60,766.9,0.13160,0.27350,0.31030,0.15990,0.2691,0.07683
212,8810703,28.11,18.47,188.50,2499.0,0.11420,0.15160,0.320100,0.15950,0.1648,...,28.11,18.47,188.50,2499.0,0.11420,0.15160,0.32010,0.15950,0.1648,0.05525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,911408,12.83,15.73,82.89,506.9,0.09040,0.08269,0.058350,0.03078,0.1705,...,14.09,19.35,93.22,605.8,0.13260,0.26100,0.34760,0.09783,0.3006,0.07802
113,864292,10.51,20.19,68.64,334.2,0.11220,0.13030,0.064760,0.03068,0.1922,...,11.16,22.75,72.62,374.4,0.13000,0.20490,0.12950,0.06136,0.2383,0.09026
243,88411702,13.75,23.77,88.54,590.0,0.08043,0.06807,0.046970,0.02344,0.1773,...,15.01,26.34,98.00,706.0,0.09368,0.14420,0.13590,0.06106,0.2663,0.06321
493,914101,12.46,12.83,78.83,477.3,0.07372,0.04043,0.007173,0.01149,0.1613,...,13.19,16.36,83.24,534.0,0.09439,0.06477,0.01674,0.02680,0.2280,0.07028
199,877500,14.45,20.22,94.49,642.7,0.09872,0.12060,0.118000,0.05980,0.1950,...,18.33,30.12,117.90,1044.0,0.15520,0.40560,0.49670,0.18380,0.4753,0.10130

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='gini',random_state=42,max_depth=5)

In [ ]:
dtc.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

In [ ]:
model = DecisionTreeRegressor(
    criterion='squared_error',
    max_depth=5,
    random_state=42)

In [ ]:
model.fit(X_train, Y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [ ]:
dtc = DecisionTreeClassifier(max_depth=None, random_state=42, class_weight='balanced')
dtc.fit(X_train_scaled, Y_train)
Y_pred=dtc.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9210526315789473

In [ ]:
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Squared Error: 0.02631578947368421
R2 Score: 0.8869047619047619

In [ ]:
from sklearn.ensemble import RandomForestClassifier
lgr = LogisticRegression(max_iter=1000)
dtc = DecisionTreeClassifier(max_depth=None,random_state=42,class_weight='balanced')
rfc = RandomForestClassifier(n_estimators=100,max_depth=None,random_state=42,class_weight='balanced')

In [ ]:
rfc=RandomForestClassifier(n_estimators=100,max_depth=None,random_state=42,class_weight='balanced')
rfc.fit(X_train_scaled,Y_train)
Y_pred=rfc.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9649122807017544

In [ ]:
rfc.fit(X_train,Y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [ ]:
#fetch the important features Based on rfc
feature_importance = rfc.feature_importances_
feature_names = X_train.columns
new_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importance})
new_df = new_df.sort_values(by='Importance', ascending=False)
print(new_df)

                    Feature  Importance
23          Worst Perimeter    0.147708
24               Worst Area    0.132315
21             Worst Radius    0.099462
8       Mean Concave Points    0.086729
28     Worst Concave Points    0.076940
27          Worst Concavity    0.054956
3            Mean Perimeter    0.050741
7            Mean Concavity    0.044143
4                 Mean Area    0.043844
14                  Area SE    0.041227
1               Mean Radius    0.032353
13             Perimeter SE    0.020066
26        Worst Compactness    0.019140
6          Mean Compactness    0.017488
11                Radius SE    0.016781
25         Worst Smoothness    0.015682
22            Worst Texture    0.014324
2              Mean Texture    0.013782
5           Mean Smoothness    0.010236
29           Worst Symmetry    0.009424
17             Concavity SE    0.008064
30  Worst Fractal Dimension    0.007366
20     Fractal Dimension SE    0.006173
12               Texture SE    0.005588
15            Smoothness SE    0.005477
9             Mean Symmetry    0.004123
16           Compactness SE    0.003378
18        Concave Points SE    0.003303
0                        ID    0.003200
10   Mean Fractal Dimension    0.003059
19              Symmetry SE    0.002928

In [ ]:
new_df.head(10)

                 Feature  Importance
23       Worst Perimeter    0.147708
24            Worst Area    0.132315
21          Worst Radius    0.099462
8    Mean Concave Points    0.086729
28  Worst Concave Points    0.076940
27       Worst Concavity    0.054956
3         Mean Perimeter    0.050741
7         Mean Concavity    0.044143
4              Mean Area    0.043844
14               Area SE    0.041227

In [ ]:
from sklearn.metrics import recall_score
recall_score(Y_test,Y_pred)

0.9761904761904762

In [ ]:
#Principle component Analysis
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X_train_pca = pca.fit_transform(X_train_scaled)
x_test_pca = pca.transform(X_test_scaled)

In [ ]:
rfc1=RandomForestClassifier(n_estimators=100,max_depth=None,random_state=42,class_weight='balanced')
rfc1.fit(X_train_scaled,Y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9649122807017544

In [ ]:
from sklearn.metrics import r2_score
r2_score(Y_test,Y_pred)

0.8492063492063492

In [ ]:
#export the model
import joblib

joblib.dump(rfc,'model.pkl')

['model.pkl']

In [ ]:
from sklearn.svm import SVC

In [ ]:
sfc = SVC()

In [ ]:
sfc.fit(X_train,Y_train)

SVC()

In [ ]:
accuracy_score(sfc.predict(X_test_scaled),Y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

0.631578947368421

In [ ]:
recall_score(sfc.predict(X_test_scaled),Y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

0.0